# -*- coding: utf-8 -*-
"""PREDICTIVE SALES FORECAST.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sCptkl5XKNB0DaNEk0hZUhagdznhRwK4

**Import Libraries**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

"""**Load Dataset**"""

df = pd.read_csv("Superstore Sales Datasets.csv")

"""**First 5 Rows**"""

df.head()

"""**Dataset Information**"""

df.info()

"""**Dataset Shape**"""

df.shape

"""**Statistical Summary**"""

df.describe()

"""**Missing Values**"""

df.isnull().sum()

df = df.dropna()

"""**Duplicate Values**"""

df.duplicated().sum()

"""**Convert Date**"""

df["Order Date"] = pd.to_datetime(df["Order Date"], dayfirst=True)

"""To Check"""

df.info()

"""**Create New Columns**"""

df["Year"] = df["Order Date"].dt.year

df["Month"] = df["Order Date"].dt.month

df["Day"] = df["Order Date"].dt.day

"""To Check"""

df.head()

"""**MONTHLY SALES**"""

monthly_sales = df.groupby("Month")["Sales"].sum()

monthly_sales

"""**MONTHLY SALES GRAPH**"""

plt.figure(figsize=(10,5))

plt.plot(monthly_sales.index,
         monthly_sales.values,
         marker='o')

plt.title("Monthly Sales Trend")

plt.xlabel("Month")

plt.ylabel("Sales")

plt.grid(True)

plt.show()

"""**CATEGORY** **SALES**"""

category_sales = df.groupby("Category")["Sales"].sum()

category_sales

"""**CATEGORY GRAPH**"""

plt.figure(figsize=(8,5))

category_sales.plot(kind="bar")

plt.title("Category Wise Sales")

plt.ylabel("Sales")

plt.show()

"""**REGION SALES**"""

region_sales = df.groupby("Region")["Sales"].sum()

region_sales.plot(kind="bar")

plt.title("Region Wise Sales")

plt.show()

"""**SEGMENT SALES**"""

segment_sales = df.groupby("Segment")["Sales"].sum()

segment_sales.plot(kind="pie",autopct="%1.1f%%")

plt.ylabel("")

plt.title("Segment Wise Sales")

plt.show()

"""**SUB CATEGORY SALES**"""

subcategory = df.groupby("Sub-Category")["Sales"].sum()

subcategory.plot(kind="bar",figsize=(12,5))

plt.title("Sub Category Sales")

plt.show()

monthly = df.groupby("Order Date")["Sales"].sum()

monthly = monthly.resample("M").sum()

monthly.head()

"""**Time Series Data Preparation**"""

# Order Date ko index bana do
df.set_index("Order Date", inplace=True)

# Monthly Sales
monthly_sales = df["Sales"].resample("M").sum()

monthly_sales.head()

"""**Time-Test Split**"""

train = monthly_sales[:int(len(monthly_sales)*0.8)]
test = monthly_sales[int(len(monthly_sales)*0.8):]

"""**Install ARIMA Library**"""

!pip install statsmodels

"""**ARIMA Model**"""

from statsmodels.tsa.arima.model import ARIMA

model = ARIMA(train, order=(5,1,0))
model_fit = model.fit()

print(model_fit.summary())

"""**Prediction**"""

forecast = model_fit.forecast(steps=len(test))

"""**Forecast Graph**"""

import matplotlib.pyplot as plt

plt.figure(figsize=(12,6))
plt.plot(train.index, train, label="Train")
plt.plot(test.index, test, label="Actual")
plt.plot(test.index, forecast, label="Forecast")

plt.legend()
plt.title("Sales Forecast")
plt.show()

"""**Future Forecast**"""

future = model_fit.forecast(steps=12)

print(future)

"""**Future Forecast Graph**"""

future.plot(figsize=(10,5))
plt.title("Future Sales Forecast")
plt.show()

"""**Model Evaluation**"""

from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np

mae = mean_absolute_error(test, forecast)
rmse = np.sqrt(mean_squared_error(test, forecast))

print("MAE:", mae)
print("RMSE:", rmse)

"""**CONCLUSION**

This project successfully developed a Predictive Sales Forecasting System using historical Superstore sales data. The dataset was cleaned, preprocessed, and analyzed to understand sales trends across different categories, regions, and customer segments. Exploratory Data Analysis (EDA) helped identify important sales patterns and seasonal variations.

A forecasting model was then applied to estimate future sales based on historical performance. The predicted results provide valuable insights into future demand, enabling businesses to make informed decisions regarding inventory management, resource allocation, and sales planning. The visualizations and forecast graphs clearly illustrate sales trends and expected future performance.

Overall, the project demonstrates how data analytics and forecasting techniques can transform raw sales data into actionable business insights. Such forecasting models help organizations improve operational efficiency, reduce uncertainty, optimize stock levels, and support strategic decision-making. With larger datasets and more advanced machine learning or deep learning models, the forecasting accuracy can be further improved in future implementations.
"""